package br.com.semanticwot.pswot.cloud.ssn.impl;

import br.com.semanticwot.pswot.cloud.ssn.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultSensor_Data_Sheet <br>
 * @version generated on Fri Mar 04 01:25:24 BRT 2016 by nailton
 */
public class DefaultSensor_Data_Sheet extends WrappedIndividualImpl implements Sensor_Data_Sheet {

    public DefaultSensor_Data_Sheet(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
