package br.com.semanticwot.pswot.cloud.ssn.impl;

import br.com.semanticwot.pswot.cloud.ssn.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultSurvival_Range <br>
 * @version generated on Fri Mar 04 01:25:24 BRT 2016 by nailton
 */
public class DefaultSurvival_Range extends WrappedIndividualImpl implements Survival_Range {

    public DefaultSurvival_Range(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
