package br.com.semanticwot.pswot.cloud.ssn.impl;

import br.com.semanticwot.pswot.cloud.ssn.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultMeasurement_Capability <br>
 * @version generated on Fri Mar 04 01:25:24 BRT 2016 by nailton
 */
public class DefaultMeasurement_Capability extends WrappedIndividualImpl implements Measurement_Capability {

    public DefaultMeasurement_Capability(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
