package br.com.semanticwot.pswot.cloud.ssn;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Mar 04 01:25:24 BRT 2016 by nailton
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Accuracy
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACCURACY.<p>
     * 
     */
    public static final OWLClass CLASS_ACCURACY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Accuracy"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#BatteryLifetime
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BATTERY_LIFETIME.<p>
     * 
     */
    public static final OWLClass CLASS_BATTERY_LIFETIME = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#BatteryLifetime"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Condition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONDITION.<p>
     * 
     */
    public static final OWLClass CLASS_CONDITION = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Condition"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Deployment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPLOYMENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPLOYMENT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Deployment"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#DeploymentRelatedProcess
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPLOYMENT_RELATED_PROCESS.<p>
     * 
     */
    public static final OWLClass CLASS_DEPLOYMENT_RELATED_PROCESS = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#DeploymentRelatedProcess"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#DetectionLimit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DETECTION_LIMIT.<p>
     * 
     */
    public static final OWLClass CLASS_DETECTION_LIMIT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#DetectionLimit"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Device
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVICE.<p>
     * 
     */
    public static final OWLClass CLASS_DEVICE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Device"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Drift
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DRIFT.<p>
     * 
     */
    public static final OWLClass CLASS_DRIFT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Drift"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#FeatureOfInterest
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FEATURE_OF_INTEREST.<p>
     * 
     */
    public static final OWLClass CLASS_FEATURE_OF_INTEREST = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#FeatureOfInterest"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Frequency
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FREQUENCY.<p>
     * 
     */
    public static final OWLClass CLASS_FREQUENCY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Frequency"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Input
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INPUT.<p>
     * 
     */
    public static final OWLClass CLASS_INPUT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Input"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Latency
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LATENCY.<p>
     * 
     */
    public static final OWLClass CLASS_LATENCY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Latency"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#MaintenanceSchedule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MAINTENANCE_SCHEDULE.<p>
     * 
     */
    public static final OWLClass CLASS_MAINTENANCE_SCHEDULE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#MaintenanceSchedule"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#MeasurementCapability
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASUREMENT_CAPABILITY.<p>
     * 
     */
    public static final OWLClass CLASS_MEASUREMENT_CAPABILITY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#MeasurementCapability"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#MeasurementProperty
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASUREMENT__PROPERTY.<p>
     * 
     */
    public static final OWLClass CLASS_MEASUREMENT__PROPERTY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#MeasurementProperty"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#MeasurementRange
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEASUREMENT__RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_MEASUREMENT__RANGE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#MeasurementRange"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Observation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBSERVATION.<p>
     * 
     */
    public static final OWLClass CLASS_OBSERVATION = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Observation"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#ObservationValue
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBSERVATION_VALUE.<p>
     * 
     */
    public static final OWLClass CLASS_OBSERVATION_VALUE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#ObservationValue"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#OperatingPowerRange
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPERATING_POWER_RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_OPERATING_POWER_RANGE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#OperatingPowerRange"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#OperatingProperty
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPERATING_PROPERTY.<p>
     * 
     */
    public static final OWLClass CLASS_OPERATING_PROPERTY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#OperatingProperty"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#OperatingRange
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OPERATING_RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_OPERATING_RANGE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#OperatingRange"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Output
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_OUTPUT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Output"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Platform
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLATFORM.<p>
     * 
     */
    public static final OWLClass CLASS_PLATFORM = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Platform"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Precision
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRECISION.<p>
     * 
     */
    public static final OWLClass CLASS_PRECISION = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Precision"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Process
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROCESS.<p>
     * 
     */
    public static final OWLClass CLASS_PROCESS = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Process"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Property
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROPERTY.<p>
     * 
     */
    public static final OWLClass CLASS_PROPERTY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Property"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Resolution
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESOLUTION.<p>
     * 
     */
    public static final OWLClass CLASS_RESOLUTION = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Resolution"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#ResponseTime
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RESPONSE_TIME.<p>
     * 
     */
    public static final OWLClass CLASS_RESPONSE_TIME = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#ResponseTime"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Selectivity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SELECTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_SELECTIVITY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Selectivity"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Sensing
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSING.<p>
     * 
     */
    public static final OWLClass CLASS_SENSING = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Sensing"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SensingDevice
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSING_DEVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SENSING_DEVICE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SensingDevice"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Sensitivity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSITIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_SENSITIVITY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Sensitivity"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Sensor
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Sensor"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SensorDataSheet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR_DATA_SHEET.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR_DATA_SHEET = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SensorDataSheet"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SensorInput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR_INPUT.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR_INPUT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SensorInput"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SensorOutput
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SENSOR_OUTPUT.<p>
     * 
     */
    public static final OWLClass CLASS_SENSOR_OUTPUT = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SensorOutput"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#Stimulus
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STIMULUS.<p>
     * 
     */
    public static final OWLClass CLASS_STIMULUS = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#Stimulus"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SurvivalProperty
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SURVIVAL_PROPERTY.<p>
     * 
     */
    public static final OWLClass CLASS_SURVIVAL_PROPERTY = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SurvivalProperty"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SurvivalRange
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SURVIVAL_RANGE.<p>
     * 
     */
    public static final OWLClass CLASS_SURVIVAL_RANGE = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SurvivalRange"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#System
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SYSTEM.<p>
     * 
     */
    public static final OWLClass CLASS_SYSTEM = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#System"));

    /* ***************************************************
     * Class http://purl.oclc.org/NET/ssnx/ssn#SystemLifetime
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SYSTEM_LIFETIME.<p>
     * 
     */
    public static final OWLClass CLASS_SYSTEM_LIFETIME = factory.getOWLClass(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#SystemLifetime"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#DesignedArtifact
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DESIGNED_ARTIFACT.<p>
     * 
     */
    public static final OWLClass CLASS_DESIGNED_ARTIFACT = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#DesignedArtifact"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Event
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EVENT.<p>
     * 
     */
    public static final OWLClass CLASS_EVENT = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Event"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#InformationObject
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INFORMATION_OBJECT.<p>
     * 
     */
    public static final OWLClass CLASS_INFORMATION_OBJECT = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#InformationObject"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Method
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class METHOD.<p>
     * 
     */
    public static final OWLClass CLASS_METHOD = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Method"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Object
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class OBJECT.<p>
     * 
     */
    public static final OWLClass CLASS_OBJECT = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Object"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#PhysicalObject
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PHYSICAL_OBJECT.<p>
     * 
     */
    public static final OWLClass CLASS_PHYSICAL_OBJECT = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#PhysicalObject"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Process
     */

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Quality
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QUALITY.<p>
     * 
     */
    public static final OWLClass CLASS_QUALITY = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Quality"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Region
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REGION.<p>
     * 
     */
    public static final OWLClass CLASS_REGION = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Region"));

    /* ***************************************************
     * Class http://www.loa-cnr.it/ontologies/DUL.owl#Situation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SITUATION.<p>
     * 
     */
    public static final OWLClass CLASS_SITUATION = factory.getOWLClass(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#Situation"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#attachedSystem
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ATTACHED_SYSTEM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ATTACHED_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#attachedSystem"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#deployedOnPlatform
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPLOYED_ON_PLATFORM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPLOYED_ON_PLATFORM = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#deployedOnPlatform"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#deployedSystem
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPLOYED_SYSTEM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPLOYED_SYSTEM = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#deployedSystem"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#deploymentProcessPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEPLOYMENT_PROCESS_PART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEPLOYMENT_PROCESS_PART = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#deploymentProcessPart"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#detects
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DETECTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DETECTS = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#detects"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#endTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property END_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_END_TIME = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#endTime"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#featureOfInterest
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FEATURE_OF_INTEREST.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FEATURE_OF_INTEREST = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#featureOfInterest"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#forProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOR_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOR_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#forProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasDeployment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_DEPLOYMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_DEPLOYMENT = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasDeployment"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasInput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_INPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_INPUT = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasInput"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementCapability
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_MEASUREMENT__CAPABILITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_MEASUREMENT__CAPABILITY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementCapability"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_MEASUREMENT_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_MEASUREMENT_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasMeasurementProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasOperatingProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_OPERATING_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_OPERATING_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasOperatingProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasOperatingRange
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_OPERATING_RANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_OPERATING_RANGE = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasOperatingRange"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasOutput
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_OUTPUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_OUTPUT = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasOutput"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasSubSystem
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SUBSYSTEM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SUBSYSTEM = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasSubSystem"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SURVIVAL_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SURVIVAL_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalRange
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SURVIVAL_RANGE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SURVIVAL_RANGE = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasSurvivalRange"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_VALUE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_VALUE = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#hasValue"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#implementedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTED_BY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#implementedBy"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#implements
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IMPLEMENTS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IMPLEMENTS = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#implements"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#inCondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IN_CONDITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IN_CONDITION = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#inCondition"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#inDeployment
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IN_DEPLOYMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IN_DEPLOYMENT = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#inDeployment"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#isProducedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PRODUCED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PRODUCED_BY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#isProducedBy"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#isPropertyOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PROPERTY_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PROPERTY_OF = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#isPropertyOf"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#isProxyFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPROXYFOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPROXYFOR = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#isProxyFor"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#madeObservation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property MADE_OBSERVATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_MADE_OBSERVATION = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#madeObservation"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observationResult
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVATION_RESULT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVATION_RESULT = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observationResult"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observationResultTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVATION_RESULT_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVATION_RESULT_TIME = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observationResultTime"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVATION_SAMPLING_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVATION_SAMPLING_TIME = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observationSamplingTime"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVEDBY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observedBy"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observedProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVED_PROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVED_PROPERTY = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observedProperty"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#observes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OBSERVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OBSERVES = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#observes"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#ofFeature
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OF_FEATURE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OF_FEATURE = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#ofFeature"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#onPlatform
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ON_PLATFORM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ON_PLATFORM = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#onPlatform"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#qualityOfObservation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property QUALITY_OF_OBSERVATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_QUALITY_OF_OBSERVATION = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#qualityOfObservation"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#sensingMethodUsed
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SENSING_METHOD_USED.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SENSING_METHOD_USED = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#sensingMethodUsed"));

    /* ***************************************************
     * Object Property http://purl.oclc.org/NET/ssnx/ssn#startTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property START_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_START_TIME = factory.getOWLObjectProperty(IRI.create("http://purl.oclc.org/NET/ssnx/ssn#startTime"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#actsFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTS_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTS_FOR = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#actsFor"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#actsThrough
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTS_THROUGH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTS_THROUGH = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#actsThrough"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#characterizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CHARACTERIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CHARACTERIZES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#characterizes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#classifies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CLASSIFIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CLASSIFIES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#classifies"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#conceptualizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONCEPTUALIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONCEPTUALIZES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#conceptualizes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#concretelyExpresses
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONCRETELY_EXPRESSES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONCRETELY_EXPRESSES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#concretelyExpresses"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#coparticipatesWith
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CO_PARTICIPATES_WITH.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CO_PARTICIPATES_WITH = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#coparticipatesWith"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#covers
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COVERS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COVERS = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#covers"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#defines
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#defines"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#definesRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINES_ROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINES_ROLE = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#definesRole"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#definesTask
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DEFINES_TASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DEFINES_TASK = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#definesTask"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#describes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DESCRIBES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DESCRIBES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#describes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#directlyFollows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DIRECTLY_FOLLOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DIRECTLY_FOLLOWS = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#directlyFollows"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#directlyPrecedes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property DIRECTLY_PRECEDES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_DIRECTLY_PRECEDES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#directlyPrecedes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#executesTask
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTES_TASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTES_TASK = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#executesTask"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#expands
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXPANDS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXPANDS = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#expands"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#expresses
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXPRESSES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXPRESSES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#expresses"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#expressesConcept
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXPRESSES_CONCEPT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXPRESSES_CONCEPT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#expressesConcept"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#farFrom
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FAR_FROM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FAR_FROM = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#farFrom"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#follows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOLLOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOLLOWS = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#follows"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasCommonBoundary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_COMMON_BOUNDARY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_COMMON_BOUNDARY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasCommonBoundary"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasComponent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_COMPONENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_COMPONENT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasComponent"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasConstituent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CONSTITUENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CONSTITUENT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasConstituent"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasConstraint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_CONSTRAINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_CONSTRAINT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasConstraint"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasLocation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_LOCATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_LOCATION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasLocation"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasMember
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_MEMBER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_MEMBER = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasMember"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasParameter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PARAMETER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PARAMETER = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasParameter"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PART = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasPart"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasParticipant
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PARTICIPANT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PARTICIPANT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasParticipant"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasPostcondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_POSTCONDITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_POSTCONDITION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasPostcondition"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasPrecondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_PRECONDITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_PRECONDITION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasPrecondition"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasQuality
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_QUALITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_QUALITY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasQuality"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasRegion
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_REGION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_REGION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasRegion"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_ROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_ROLE = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasRole"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasSetting
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_SETTING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_SETTING = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasSetting"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#hasTask
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HAS_TASK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HAS_TASK = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasTask"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#includesAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCLUDES_ACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCLUDES_ACTION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#includesAction"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#includesAgent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCLUDES_AGENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCLUDES_AGENT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#includesAgent"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#includesEvent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCLUDES_EVENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCLUDES_EVENT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#includesEvent"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#includesObject
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCLUDES_OBJECT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCLUDES_OBJECT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#includesObject"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#includesTime
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INCLUDES_TIME.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INCLUDES_TIME = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#includesTime"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#introduces
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INTRODUCES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INTRODUCES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#introduces"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#involvesAgent
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVES_AGENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVES_AGENT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#involvesAgent"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isAbout
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ABOUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ABOUT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isAbout"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isActionIncludedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ACTION_INCLUDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ACTION_INCLUDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isActionIncludedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isAgentIncludedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_AGENT_INCLUDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_AGENT_INCLUDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isAgentIncludedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isAgentInvolvedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_AGENT_INVOLVED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_AGENT_INVOLVED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isAgentInvolvedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isCharacterizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CHARACTERIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CHARACTERIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isCharacterizedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isClassifiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CLASSIFIED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CLASSIFIED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isClassifiedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isComponentOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_COMPONENT_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_COMPONENT_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isComponentOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConceptExpressedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONCEPT_EXPRESSED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONCEPT_EXPRESSED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConceptExpressedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConceptUsedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONCEPT_USED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONCEPT_USED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConceptUsedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConceptualizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONCEPTUALIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONCEPTUALIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConceptualizedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConcretelyExpressedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONCRETELY_EXPRESSED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONCRETELY_EXPRESSED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConcretelyExpressedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConstituentOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONSTITUENT_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONSTITUENT_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConstituentOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isConstraintFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_CONSTRAINT_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_CONSTRAINT_FOR = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isConstraintFor"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isCoveredBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_COVERED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_COVERED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isCoveredBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isDefinedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_DEFINED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_DEFINED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isDefinedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isDescribedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_DESCRIBED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_DESCRIBED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isDescribedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isEventIncludedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_EVENT_INCLUDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_EVENT_INCLUDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isEventIncludedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isExecutedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_EXECUTED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_EXECUTED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isExecutedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isExpandedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_EXPANDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_EXPANDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isExpandedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isExpressedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_EXPRESSED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_EXPRESSED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isExpressedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isIntroducedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_INTRODUCED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_INTRODUCED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isIntroducedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isLocationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_LOCATION_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_LOCATION_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isLocationOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isMemberOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_MEMBER_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_MEMBER_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isMemberOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isObjectIncludedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_OBJECT_INCLUDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_OBJECT_INCLUDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isObjectIncludedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isObservableAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_OBSERVABLE_AT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_OBSERVABLE_AT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isObservableAt"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isParameterFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PARAMETER_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PARAMETER_FOR = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isParameterFor"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isParametrizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PARAMETRIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PARAMETRIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isParametrizedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PART_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PART_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isPartOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isParticipantIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PARTICIPANT_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PARTICIPANT_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isParticipantIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isPostconditionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_POSTCONDITION_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_POSTCONDITION_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isPostconditionOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isPreconditionOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_PRECONDITION_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_PRECONDITION_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isPreconditionOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isQualityOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_QUALITY_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_QUALITY_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isQualityOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRealizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_REALIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_REALIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRealizedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isReferenceOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_REFERENCE_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_REFERENCE_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isReferenceOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isReferenceOfInformationRealizedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_REFERENCE_OF_INFORMATION_REALIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_REFERENCE_OF_INFORMATION_REALIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isReferenceOfInformationRealizedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRegionFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_REGION_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_REGION_FOR = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRegionFor"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRelatedToConcept
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_RELATED_TO_CONCEPT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_RELATED_TO_CONCEPT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRelatedToConcept"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRelatedToDescription
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_RELATED_TO_DESCRIPTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_RELATED_TO_DESCRIPTION = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRelatedToDescription"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRoleDefinedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ROLE_DEFINED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ROLE_DEFINED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRoleDefinedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isRoleOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_ROLE_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_ROLE_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isRoleOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isSatisfiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SATISFIED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SATISFIED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isSatisfiedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isSettingFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SETTING_FOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SETTING_FOR = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isSettingFor"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isSpecializedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SPECIALIZED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SPECIALIZED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isSpecializedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isSubordinatedTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SUBORDINATED_TO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SUBORDINATED_TO = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isSubordinatedTo"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isSuperordinatedTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_SUPERORDINATED_TO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_SUPERORDINATED_TO = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isSuperordinatedTo"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isTaskDefinedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_TASK_DEFINED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_TASK_DEFINED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isTaskDefinedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isTaskOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_TASK_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_TASK_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isTaskOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isTimeIncludedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_TIME_INCLUDED_IN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_TIME_INCLUDED_IN = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isTimeIncludedIn"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isTimeOfObservationOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_TIME_OF_OBSERVATION_OF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_TIME_OF_OBSERVATION_OF = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isTimeOfObservationOf"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#isUnifiedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IS_UNIFIED_BY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IS_UNIFIED_BY = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#isUnifiedBy"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#nearTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEAR_TO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEAR_TO = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#nearTo"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#overlaps
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OVERLAPS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OVERLAPS = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#overlaps"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#parametrizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARAMETRIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARAMETRIZES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#parametrizes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#precedes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRECEDES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRECEDES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#precedes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#realizes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REALIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REALIZES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#realizes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#realizesInformationAbout
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property REALIZES_INFORMATION_ABOUT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_REALIZES_INFORMATION_ABOUT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#realizesInformationAbout"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#satisfies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SATISFIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SATISFIES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#satisfies"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#specializes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SPECIALIZES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SPECIALIZES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#specializes"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#unifies
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property UNIFIES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_UNIFIES = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#unifies"));

    /* ***************************************************
     * Object Property http://www.loa-cnr.it/ontologies/DUL.owl#usesConcept
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property USES_CONCEPT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_USES_CONCEPT = factory.getOWLObjectProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#usesConcept"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasDataValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_DATA_VALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_DATA_VALUE = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasDataValue"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasEventDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_EVENT_DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_EVENT_DATE = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasEventDate"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasIntervalDate
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_INTERVAL_DATE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_INTERVAL_DATE = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasIntervalDate"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasParameterDataValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PARAMETER_DATA_VALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PARAMETER_DATA_VALUE = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasParameterDataValue"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasProxy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_PROXY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_PROXY = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasProxy"));

    /* ***************************************************
     * Data Property http://www.loa-cnr.it/ontologies/DUL.owl#hasRegionDataValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HAS_REGION_DATA_VALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HAS_REGION_DATA_VALUE = factory.getOWLDataProperty(IRI.create("http://www.loa-cnr.it/ontologies/DUL.owl#hasRegionDataValue"));


}
